"""add users and workspaces tables

Revision ID: bce955a22142
Revises: 7d8471eddb48
Create Date: 2026-07-29 15:38:55.583953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce955a22142'
down_revision: Union[str, Sequence[str], None] = '7d8471eddb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_workspaces_slug'), 'workspaces', ['slug'], unique=True, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_workspaces_slug'), table_name='workspaces', schema='app')
    op.drop_index(op.f('ix_app_workspaces_owner_id'), table_name='workspaces', schema='app')
    op.drop_table('workspaces', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    # ### end Alembic commands ###
